[package]
name = "icp_token_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.4"
ic-cdk-macros = "0.4"
candid = "0.7"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
